name: segcolr-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=21.3.1
  - numpy=1.23.5
  - opencv=4.5.5
  - pillow=9.0.1
  - matplotlib=3.5.1
  - plotly=5.6.0
  - requests=2.27.1
  - pip:
    - torch==1.10.2
    - torchvision==0.11.3
    - transformers==4.17.0
    # - git+https://github.com/huggingface/transformers
